version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.41
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/vscode"
    versions:
    - 1.53.0
    - 1.54.0
    - 1.55.0
  - dependency-name: vscode-test
    versions:
    - 1.5.0
    - 1.5.1
    - 1.5.2
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
    - 8.2.2
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
    - 8.3.2
