language: node_js
install: skip
node_js: node
cache: yarn

script:
  - npm ci
  - npm run build
  - npm run test

jobs:
  include:
    - os: osx
    - os: linux
      install:
        - export DISPLAY=':99.0'
        - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
