name: 'vsix'
on: [ push, pull_request ]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and test vsc-hdl
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm ci
        npm run compile
        npm run test

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - uses: actions/checkout@v1
    - name: build VSIX package
      run: |
        sudo npm install -g vsce
        sudo chown -R $USER:$(id -gn $USER) $HOME/.config
        npm ci
        vsce package
        mkdir vsc-hdl-vsix
        mv vsc-hdl-*.vsix vsc-hdl-vsix
    - uses: actions/upload-artifact@master
      with:
        name: vsc-hdl-vsix
        path: vsc-hdl-vsix
